services:
  distributedratelimiter:
    image: distributedratelimiter
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      default:
        aliases:
            - redis
    
